---
version: 1
name: 'Create Independent Service'
worker_definition:
  process_engine: 'zeebe'
  worker_id: 'sc-createindependentserviceprocessadapter'
  process: 'sc-createindependentserviceprocess-common-stable'
  max_tasks: 1
  max_parallel_tasks_per_handler: 1
  lock_duration_seconds: 120
