---
subscription_points: 
  - sc-createindependentserviceprocess-common-stable_create_service_account
command:
  request: create_service_account
  reply_to:
    type: http
    identification: caller_connection  
  variables:
    - name: service_identification
      source: process
      value: 'na'
      type: string
      example: 'tearoom-notifications'
  handler:
    type: rest
    reactor:
      domain: sc
      context: adolfHandler
      purpose: common
      version: stable
      environment:
        space: dev1
        tier: services
    implementation_note: 'Handler for Adolf service'
  security:
    handler:
      tgt_audience_root: null
    command:
      tgt_audience_root: null
response:
mock:
  default_response_type: 'ok'
  sleep_before_execution_seconds: 1
