---
subscription_points: 
  - sc-createindependentserviceprocess-common-stable_notify_service_created
  - sc-createindependentserviceprocess-common-stable_notify_bundle_added_to_environment
command:
  request: notify_slack
  reply_to:
    type: http
    identification: caller_connection  
  variables:
    - name: channel
      source: header
      value: 'na'
      type: string
      example: 'tearoom_notifications'
    - name: title
      source: header
      value: 'na'
      type: string
      example: 'Message Title'
    - name: text
      source: process
      value: 'na'
      type: string
      example: 'This is the text of the message'
    - name: sender
      source: header
      value: 'na'
      type: string
      example: 'SenderId'
  handler:
    type: rest
    reactor:
      domain: hr
      context: personaggregate
      purpose: common
      version: stable
      environment:
        space: ict
        tier: dev2
    implementation_note: 'Sends a notification to Slack'
  security:
    handler:
      tgt_audience_root: null
    command:
      tgt_audience_root: null
response:
mock:
  default_response_type: 'ok'
  sleep_before_execution_seconds: 1
